# Site settings
title: 舒洪凡 Blog
SEOTitle: 舒洪凡的博客 | SHF Blog
header-img: img/home-bg.jpg
email: shfshuhongfan@gmail.com
description: "舒洪凡 | SHF | shuhongfan | 舒洪凡的博客 | 舒洪凡 Blog | shfshuhongfan | 这里是 @SHF舒洪凡 的个人博客，与你一起发现更大的世界。"
keyword: "舒洪凡, SHF舒洪凡, SHF, shuhongfan, @shf, @shuhongfan, 舒洪凡的博客, 舒洪凡 Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://shuhongfan.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     shuhongfan
zhihu_username:     shuhongfan
github_username:    shuhongfan
twitter_username:   shuhongfan_
facebook_username:  shuhongfans
linkedin_username:  shuhongfan



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: shuhongfan

# Netease settings
netease_comment: true



# Analytics settings
# Baidu Analytics
ba_track_id: c7f2ab34fede3d8d7f9f02a83e2fa803

# Google Analytics
ga_track_id: 'G-E0CYX36DGD'            # Format: UA-xxxxxx-xx
ga_domain: shuhongfan.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/shf.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
  {
    title: "GitHub博客",
    href: "https://github.com/shuhongfan"
  },{
    title: "GitHub仓库",
    href: "http://shuhongfan.github.io/"
  },{
    title: "Gitee博客",
    href: "https://gitee.com/shuhongfan"
  },{
    title: "Gitee仓库",
    href: "http://shuhongfan.gitee.io/"
  },{
    title: "博客园",
    href: "https://www.cnblogs.com/shuhongfan/"
  },{
    title: "CSDN",
    href: "https://blog.csdn.net/qq_26347769/"
  },{
    title: "新浪博客",
    href: "http://blog.sina.com.cn/shuhongfan"
  },{
    title: "优酷视频",
    href: "http://i.youku.com/shuhongfan"
  },{
    title: "爱奇艺视频",
    href: "https://www.iqiyi.com/u/2018595985"
  },{
    title: "腾讯视频",
    href: "https://v.qq.com/s/videoplus/144170183"
  },{
    title: "搜狐视频",
    href: "http://tv.sohu.com/user/326360003"
  },{
    title: "西瓜视频",
    href: "https://www.ixigua.com/home/3343060935/"
  }
]
